rewrite ^${HAFBE_API_BASE_PATH}/operation-type-counts /rpc/get_latest_blocks break;
# endpoint for get ${HAFBE_API_BASE_PATH}/operation-type-counts

rewrite ^${HAFBE_API_BASE_PATH}/input-type/([^/]+) /rpc/get_input_type?input-value=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/input-type/{input-value}

rewrite ^${HAFBE_API_BASE_PATH}/last-synced-block /rpc/get_hafbe_last_synced_block break;
# endpoint for get ${HAFBE_API_BASE_PATH}/last-synced-block

rewrite ^${HAFBE_API_BASE_PATH}/version /rpc/get_hafbe_version break;
# endpoint for get ${HAFBE_API_BASE_PATH}/version

rewrite ^${HAFBE_API_BASE_PATH}/operation-type-statistics /rpc/get_operation_type_statistics break;
# endpoint for get ${HAFBE_API_BASE_PATH}/operation-type-statistics

rewrite ^${HAFBE_API_BASE_PATH}/transaction-statistics /rpc/get_transaction_statistics break;
# endpoint for get ${HAFBE_API_BASE_PATH}/transaction-statistics

rewrite ^${HAFBE_API_BASE_PATH}/proposals/([^/]+)/votes/history /rpc/get_proposal_votes_history?proposal-id=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/proposals/{proposal-id}/votes/history

rewrite ^${HAFBE_API_BASE_PATH}/proposals/votes /rpc/get_proposal_votes break;
# endpoint for get ${HAFBE_API_BASE_PATH}/proposals/votes

rewrite ^${HAFBE_API_BASE_PATH}/proposals /rpc/get_proposals break;
# endpoint for get ${HAFBE_API_BASE_PATH}/proposals

rewrite ^${HAFBE_API_BASE_PATH}/block-search /rpc/get_block_by_op?path-filter=$path_filters break;
# endpoint for get ${HAFBE_API_BASE_PATH}/block-search

rewrite ^${HAFBE_API_BASE_PATH}/total_wallet_addresses /rpc/get_total_wallet_addresses break;
# endpoint for get ${HAFBE_API_BASE_PATH}/total_wallet_addresses

rewrite ^${HAFBE_API_BASE_PATH}/accounts/([^/]+)/operations/comments/([^/]+) /rpc/get_comment_operations?account-name=$1&permlink=$2 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/accounts/{account-name}/operations/comments/{permlink}

rewrite ^${HAFBE_API_BASE_PATH}/accounts/([^/]+)/comment-permlinks /rpc/get_comment_permlinks?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/accounts/{account-name}/comment-permlinks

rewrite ^${HAFBE_API_BASE_PATH}/accounts/([^/]+)/proxy-power /rpc/get_account_proxies_power?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/accounts/{account-name}/proxy-power

rewrite ^${HAFBE_API_BASE_PATH}/accounts/([^/]+)/authority /rpc/get_account_authority?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/accounts/{account-name}/authority

rewrite ^${HAFBE_API_BASE_PATH}/accounts/([^/]+) /rpc/get_account?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/accounts/{account-name}

rewrite ^${HAFBE_API_BASE_PATH}/witnesses/([^/]+)/votes/history /rpc/get_witness_votes_history?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/witnesses/{account-name}/votes/history

rewrite ^${HAFBE_API_BASE_PATH}/witnesses/([^/]+)/voters/count /rpc/get_witness_voters_num?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/witnesses/{account-name}/voters/count

rewrite ^${HAFBE_API_BASE_PATH}/witnesses/([^/]+)/voters /rpc/get_witness_voters?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/witnesses/{account-name}/voters

rewrite ^${HAFBE_API_BASE_PATH}/witnesses/([^/]+) /rpc/get_witness?account-name=$1 break;
# endpoint for get ${HAFBE_API_BASE_PATH}/witnesses/{account-name}

rewrite ^${HAFBE_API_BASE_PATH}/witnesses /rpc/get_witnesses break;
# endpoint for get ${HAFBE_API_BASE_PATH}/witnesses

rewrite ^${HAFBE_API_BASE_PATH}/rpc/(.*)$ /rpc/$1 break;
# direct RPC calls: ${HAFBE_API_BASE_PATH}/rpc/function_name

rewrite ^${HAFBE_API_BASE_PATH}/$ / break;
# endpoint for openapi spec itself

rewrite ^${HAFBE_API_BASE_PATH}/(.*)$ /rpc/$1 break;
# default endpoint for everything else
